services:
  rpi-cloud-init-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rpi-cloud-init-generator
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    restart: unless-stopped
    environment:
      - TZ=UTC
